# Generated by Django 5.2.6 on 2025-10-15 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 15, 3, 13, 49, 239042, tzinfo=datetime.timezone.utc)),
        ),
    ]
